apiVersion: v1
kind: Service
metadata:
  name: {{ include "kwirth.fullname" . }}-svc
  labels:
    {{- include "kwirth.labels" . | nindent 4 }}
  {{- with .Values.kwirth.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.kwirth.service.type }}
  selector:
    {{- include "kwirth.selectorLabels" . | nindent 4 }}
  ports:
    - name: kwirth-port
      protocol: TCP
      port: {{ .Values.kwirth.service.port }}
      targetPort: kwirth
