{{- if include "kwirth.serviceAccountCreate" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kwirth.serviceAccountName" . }}
  labels:
    {{- include "kwirth.labels" . | nindent 4 }}
  {{- $annotations := include "kwirth.serviceAccountAnnotations" . }}
  {{- if and $annotations (ne $annotations "{}") }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
{{- end }}
