import { IInstanceMessage } from '@kwirthmagnify/kwirth-common'

// ============================================================================
// mIRC wire protocol — shared between front and back.
//
// Every message rides inside the standard Kwirth IInstanceMessage envelope
// (channel/instance/type/flow/action) and adds a `msgtype` discriminator plus
// a typed payload, exactly like the Echo plugin does with 'echomessage'.
// ============================================================================

export type TMircMsgType =
    // front -> back (commands)
    | 'mirc-hello'      // announce my nick, request initial roster + flush my mailbox
    | 'mirc-send'       // send a DM to a user
    | 'mirc-read'       // mark messages from a peer as read
    | 'mirc-roster'     // (re)request the roster
    // back -> front (events)
    | 'mirc-roster-data' // full roster snapshot
    | 'mirc-presence'    // a single user went online/offline
    | 'mirc-message'     // an incoming DM (delivered live or flushed from the mailbox)
    | 'mirc-ack'         // server accepted+stored a message I sent  (single check)
    | 'mirc-receipt'     // delivery/read state change for a message I sent
    | 'mirc-error'

export type TMircState = 'sent' | 'delivered' | 'read' | 'failed'

// A user as seen in the roster. `cluster` is filled in by the front (the back
// only knows about itself); the back leaves it empty.
export interface IMircUser {
    nick: string
    online: boolean
    cluster?: string
}

// The canonical message record. `ts` is ALWAYS the server clock in UTC ISO-8601
// (sealed by the back at acceptance time) so ordering is consistent for both
// parties regardless of client clock skew.
export interface IMircMessageRecord {
    msgId: string
    from: string
    to: string
    ts: string          // server UTC, ISO-8601, authoritative for ordering
    body: string
    state: TMircState
}

// ---- front -> back ----------------------------------------------------------

export interface IMircHello extends IInstanceMessage {
    msgtype: 'mirc-hello'
    nick: string
}

export interface IMircSend extends IInstanceMessage {
    msgtype: 'mirc-send'
    msgId: string       // generated by the sender front (also used for idempotency)
    to: string
    body: string
}

export interface IMircRead extends IInstanceMessage {
    msgtype: 'mirc-read'
    peer: string        // the user whose messages I just read
    msgIds: string[]
}

export interface IMircRosterRequest extends IInstanceMessage {
    msgtype: 'mirc-roster'
}

// ---- back -> front ----------------------------------------------------------

export interface IMircRosterData extends IInstanceMessage {
    msgtype: 'mirc-roster-data'
    users: IMircUser[]
}

export interface IMircPresence extends IInstanceMessage {
    msgtype: 'mirc-presence'
    nick: string
    online: boolean
}

export interface IMircMessage extends IInstanceMessage {
    msgtype: 'mirc-message'
    record: IMircMessageRecord
}

export interface IMircAck extends IInstanceMessage {
    msgtype: 'mirc-ack'
    msgId: string
    ts: string          // authoritative server ts assigned to the message
    state: 'sent' | 'failed'
    reason?: string
}

export interface IMircReceipt extends IInstanceMessage {
    msgtype: 'mirc-receipt'
    msgId: string
    to: string          // the recipient the receipt refers to
    state: 'delivered' | 'read'
    ts: string
}

export interface IMircError extends IInstanceMessage {
    msgtype: 'mirc-error'
    msgId?: string
    text: string
}

export type TMircFrontToBack = IMircHello | IMircSend | IMircRead | IMircRosterRequest
export type TMircBackToFront = IMircRosterData | IMircPresence | IMircMessage | IMircAck | IMircReceipt | IMircError
export type TMircAny = TMircFrontToBack | TMircBackToFront

export const MIRC_CHANNEL_ID = 'mirc'
